// v1.1 — Program → Import Program. Mounted by js/views/program.js when the
// hash carries `?import=1` (the same hash-query sub-screen pattern the Day
// editor already uses), so no router/config change is needed and the
// Program tab stays highlighted.
//
// Flow: choose a .json/.csv file → parse + validate (pure,
// js/utils/programImport.js — nothing is written) → preview → the user
// confirms "Import Program" → ONE all-or-nothing transaction
// (programService.importProgram). An id that already exists is never
// overwritten: the user must pick a new id first.
//
// Every value that came from the file is rendered through escapeHtml.
import { getCurrentUser } from '../core/auth.js';
import { listPrograms, importProgram, ProgramIdConflictError } from '../services/programService.js';
import { getUserProfile } from '../services/userService.js';
import {
  prepareProgramImport, summarizeImportPlan, withProgramId,
  CSV_COLUMNS, CSV_TEMPLATE, IMPORT_LIMITS,
} from '../utils/programImport.js';
import { basisLabel } from '../utils/programDisplay.js';
import { generateProgramId } from '../utils/programEditModel.js';
import { downloadCsv } from '../utils/download.js';
import { escapeHtml } from '../utils/dom.js';

const LOAD_TYPE_LABELS = {
  none: 'No load',
  bodyweight: 'Bodyweight',
  fixed: 'Fixed kg',
  percent: '% of 1RM',
  percentRange: '% of 1RM range',
  sets: 'Warm-up ramp (fixed kg)',
};

function issueListHtml(items, cls) {
  if (!items?.length) return '';
  return `<ul class="import-issues ${cls}">${items.map((i) => `
    <li>${i.where ? `<span class="import-issue-where">${escapeHtml(i.where)}</span> — ` : ''}${escapeHtml(i.message)}</li>`).join('')}</ul>`;
}

function formatHelpHtml() {
  return `
    <details class="card import-help">
      <summary>File formats</summary>
      <p><strong>JSON</strong> is the app's native program format — the same structure as the
      built-in program file, including block-driven, weekly %-range, warm-up ramps, RPE and notes.</p>
      <p><strong>CSV</strong> is a simpler spreadsheet format: one row per exercise, per day, per week.
      Identical rows across weeks are merged automatically. It covers fixed kg, % of 1RM, % ranges,
      bodyweight, timed holds, rep ranges, RPE/RIR targets and notes.</p>
      <p class="card-notice import-json-only"><strong>JSON only:</strong> block-driven lifts (top single + backoff +
      snatch-grip + warm-up ramp scaled to your 1RM), weekly %-range blocks with their own sets×reps per week,
      exercise library/cues, and program notes &amp; decision rules. Use JSON for programs like the built-in
      Deadlift program — CSV cannot represent them.</p>
      <div class="import-columns">
        ${CSV_COLUMNS.map((c) => `
          <div class="import-column">
            <code>${escapeHtml(c.name)}</code>${c.required ? ' <span class="badge-active">required</span>' : ''}
            <div class="text-muted">${escapeHtml(c.help)}</div>
          </div>`).join('')}
      </div>
      <button type="button" class="btn btn-secondary" id="csv-template-btn">Download CSV template</button>
    </details>`;
}

function summaryHtml(summary) {
  const loadBits = Object.entries(summary.loadTypeCounts)
    .map(([type, n]) => `${escapeHtml(LOAD_TYPE_LABELS[type] ?? type)}: ${n}`)
    .join(' · ');
  const weekNotes = [
    summary.deloadWeeks.length ? `Deload: week ${summary.deloadWeeks.join(', ')}` : '',
    summary.prWeeks.length ? `PR attempt: week ${summary.prWeeks.join(', ')}` : '',
  ].filter(Boolean).join(' · ');
  const missingMax = summary.percentBases.filter((b) => !b.hasCurrentMax);
  return `
    <div class="card card-primary">
      <div class="card-label">Preview — nothing has been saved yet</div>
      <h3 class="card-title">${escapeHtml(summary.name)}</h3>
      <div class="account-row"><span class="text-muted">Program id</span><strong>${escapeHtml(summary.programId)}</strong></div>
      <div class="account-row"><span class="text-muted">Version</span><strong>${escapeHtml(summary.version ?? '—')}</strong></div>
      <div class="account-row"><span class="text-muted">Format</span><strong>${escapeHtml(summary.format.toUpperCase())}</strong></div>
      ${summary.sourceFile ? `<div class="account-row"><span class="text-muted">Source</span><strong class="import-meta">${escapeHtml(summary.sourceFile)}</strong></div>` : ''}
      ${summary.generatedBy ? `<div class="account-row"><span class="text-muted">Generated by</span><strong class="import-meta">${escapeHtml(summary.generatedBy)}</strong></div>` : ''}
      <div class="account-row"><span class="text-muted">Weeks</span><strong>${summary.weekCount}</strong></div>
      <div class="account-row"><span class="text-muted">Training days</span><strong>${summary.dayCount}</strong></div>
      <div class="account-row"><span class="text-muted">Exercises</span><strong>${summary.exercises.length}</strong></div>
      ${weekNotes ? `<p class="text-muted">${escapeHtml(weekNotes)}</p>` : ''}
    </div>

    <div class="card">
      <h3>Days</h3>
      ${summary.days.map((d) => `
        <div class="import-day">
          <div><strong>Day ${d.order}: ${escapeHtml(d.name)}</strong></div>
          <div class="text-muted">${d.exerciseNames.map((n) => escapeHtml(n)).join(', ')}</div>
        </div>`).join('')}
    </div>

    <div class="card">
      <h3>Loads &amp; calculation</h3>
      <p class="text-muted">${loadBits || 'No loads'}${summary.rpeTargets ? ` · RPE targets: ${summary.rpeTargets}` : ''}${summary.warmupRamps ? ` · Warm-up ramps: ${summary.warmupRamps}` : ''}</p>
      ${summary.percentBases.length ? `
        <p>Percentage loads are calculated from your <em>current</em> 1RM for:</p>
        <ul class="notice-list">
          ${summary.percentBases.map((b) => `<li>${escapeHtml(basisLabel(b.exerciseId, b.name))} — ${b.hasCurrentMax ? '1RM on file ✓' : '<span class="import-missing">no 1RM on file yet</span>'}</li>`).join('')}
        </ul>
        ${missingMax.length ? '<p class="text-muted">You can still import it — set the missing 1RMs on Profile before starting a workout from this program.</p>' : ''}` : ''}
      ${summary.programNotes || summary.decisionRules.length ? `
        <h3>Notes &amp; decision rules</h3>
        ${summary.programNotes ? `<p class="program-notes">${escapeHtml(summary.programNotes)}</p>` : ''}
        ${summary.decisionRules.length ? `<ul class="notice-list">${summary.decisionRules.map((r) => `<li>${escapeHtml(r)}</li>`).join('')}</ul>` : ''}` : ''}
      ${summary.importMaxes ? `
        <p class="text-muted">Written for 1RMs of ${Object.entries(summary.importMaxes).map(([id, kg]) => `${escapeHtml(basisLabel(id))} ${escapeHtml(kg)} kg`).join(', ')}
        — reference only; your own 1RMs are used and are not changed by importing.</p>` : ''}
      <p class="text-muted">Rounding: barbell ${escapeHtml(summary.roundingRules.barbell)} kg · dumbbell ${escapeHtml(summary.roundingRules.dumbbell)} kg · machine ${escapeHtml(summary.roundingRules.machine)} kg</p>
    </div>`;
}

export async function mount(root) {
  const uid = getCurrentUser().uid;
  root.innerHTML = '<div class="loading-state" role="status">Loading…</div>';

  let existingIds = [];
  let currentMaxes = {};
  try {
    const [programs, profile] = await Promise.all([listPrograms(uid), getUserProfile(uid)]);
    existingIds = programs.map((p) => p.id);
    currentMaxes = profile?.currentMaxes ?? {};
  } catch (err) {
    console.error('programImport: could not load existing programs', err);
    root.innerHTML = `
      <section class="program-view">
        <a href="#/program" class="text-muted">&larr; Back to Program</a>
        <h2>Import Program</h2>
        <p class="login-error">Could not load your existing programs, so importing is unavailable right now. ${escapeHtml(err.message)}</p>
      </section>`;
    return;
  }

  root.innerHTML = `
    <section class="program-view program-import">
      <a href="#/program" class="text-muted">&larr; Back to Program</a>
      <h2>Import Program</h2>
      <div id="import-body"></div>
    </section>`;
  const body = root.querySelector('#import-body');

  function renderChoose(message = '') {
    body.innerHTML = `
      <div class="card">
        <p>Add a new training program from a <strong>.json</strong> or <strong>.csv</strong> file.
        It is added as a new program — your existing programs, workout history, 1RMs and bodyweight are never changed.</p>
        <input type="file" id="import-file-input" accept=".json,.csv,application/json,text/csv" hidden>
        <button type="button" class="btn btn-primary" id="import-choose-btn">Choose File…</button>
        <p class="form-status" id="import-status" role="status">${escapeHtml(message)}</p>
      </div>
      ${formatHelpHtml()}`;
    const input = body.querySelector('#import-file-input');
    body.querySelector('#import-choose-btn').addEventListener('click', () => input.click());
    input.addEventListener('change', () => {
      const file = input.files?.[0];
      if (file) handleFile(file);
    });
    body.querySelector('#csv-template-btn').addEventListener('click', () => {
      downloadCsv('program-import-template.csv', CSV_TEMPLATE);
    });
  }

  async function handleFile(file) {
    const status = body.querySelector('#import-status');
    if (status) status.textContent = 'Reading file…';
    if (file.size > IMPORT_LIMITS.maxFileBytes) {
      renderErrors(file.name, { errors: [{ where: 'File', message: `The file is too large (max ${Math.round(IMPORT_LIMITS.maxFileBytes / 1024)} KB).` }], warnings: [] });
      return;
    }
    let text;
    try {
      text = await file.text();
    } catch (err) {
      renderErrors(file.name, { errors: [{ where: 'File', message: `Could not read the file: ${err.message}` }], warnings: [] });
      return;
    }
    const validation = prepareProgramImport({
      fileName: file.name, text, byteLength: file.size, existingProgramIds: existingIds,
    });
    if (validation.errors.length) {
      renderErrors(file.name, validation);
      return;
    }
    renderPreview(file.name, validation);
  }

  function renderErrors(fileName, validation) {
    body.innerHTML = `
      <div class="card import-error-card">
        <h3>This file can't be imported</h3>
        <p class="text-muted">${escapeHtml(fileName)} — nothing was saved. Fix the problems below and choose the file again.</p>
        ${issueListHtml(validation.errors, 'is-error')}
        ${validation.moreErrors ? `<p class="text-muted">…and ${validation.moreErrors} more.</p>` : ''}
        ${validation.warnings?.length ? `<h4>Warnings</h4>${issueListHtml(validation.warnings, 'is-warning')}` : ''}
        <button type="button" class="btn btn-secondary" id="import-again-btn">Choose Another File</button>
      </div>`;
    body.querySelector('#import-again-btn').addEventListener('click', () => renderChoose());
  }

  function renderPreview(fileName, validation) {
    const { conflict } = validation;
    const summary = summarizeImportPlan(validation.plan, { currentMaxes });
    body.innerHTML = `
      ${conflict ? `
        <div class="card card-notice import-conflict">
          <h3>Program id already in use</h3>
          <p>You already have a program with the id <strong>${escapeHtml(conflict.programId)}</strong>.
          Importing never overwrites an existing program — choose a different id for this one.</p>
          <div class="form-row">
            <input type="text" id="import-id-input" value="${escapeHtml(conflict.suggestion)}" aria-label="New program id" autocomplete="off" spellcheck="false">
            <button type="button" class="btn btn-primary" id="import-id-apply">Use this id</button>
          </div>
          <p class="login-error" id="import-id-error" role="alert"></p>
        </div>` : ''}
      ${summaryHtml(summary)}
      ${validation.warnings?.length ? `<div class="card"><h3>Warnings</h3>${issueListHtml(validation.warnings, 'is-warning')}</div>` : ''}
      <div class="card">
        <p class="text-muted">From ${escapeHtml(fileName)}. The program is added to your list; your active program doesn't change until you choose Set Active.</p>
        <div class="btn-stack">
          <button type="button" class="btn btn-primary btn-large" id="import-confirm-btn" ${conflict ? 'disabled' : ''}>Import Program</button>
          <button type="button" class="btn btn-secondary" id="import-cancel-btn">Cancel</button>
        </div>
        <p class="form-status" id="import-confirm-status" role="status"></p>
      </div>`;

    body.querySelector('#import-cancel-btn').addEventListener('click', () => renderChoose());

    body.querySelector('#import-id-apply')?.addEventListener('click', () => {
      const input = body.querySelector('#import-id-input');
      const result = withProgramId(validation, input.value, existingIds);
      if (!result.ok) {
        body.querySelector('#import-id-error').textContent = result.error;
        return;
      }
      renderPreview(fileName, result.validation);
    });

    body.querySelector('#import-confirm-btn').addEventListener('click', async () => {
      const btn = body.querySelector('#import-confirm-btn');
      const status = body.querySelector('#import-confirm-status');
      body.querySelectorAll('button, input').forEach((el) => { el.disabled = true; });
      status.textContent = 'Importing…';
      try {
        const programId = await importProgram(uid, validation.plan);
        existingIds = [...existingIds, programId];
        renderSuccess(programId, summary.name);
      } catch (err) {
        console.error('programImport: import failed', err);
        if (err instanceof ProgramIdConflictError) {
          // Created elsewhere (another tab/device) after the preview was
          // shown — the transaction refused to overwrite it. Ask for a new id.
          existingIds = [...new Set([...existingIds, err.programId])];
          renderPreview(fileName, {
            ...validation,
            ok: false,
            conflict: { programId: err.programId, suggestion: generateProgramId(err.programId, existingIds) },
          });
          return;
        }
        const offline = typeof navigator !== 'undefined' && navigator.onLine === false;
        status.classList.add('login-error');
        status.textContent = offline
          ? 'Importing a program needs an internet connection. Nothing was saved — try again when you\'re back online.'
          : `Import failed — nothing was saved. ${err.message}`;
        body.querySelectorAll('button, input').forEach((el) => { el.disabled = false; });
        if (btn && validation.conflict) btn.disabled = true;
      }
    });
  }

  function renderSuccess(programId, name) {
    body.innerHTML = `
      <div class="card card-primary">
        <h3 class="card-title">Program imported</h3>
        <p>“${escapeHtml(name)}” is now in your programs. Your current program and all your history are unchanged —
        open it and choose <strong>Set Active</strong> when you want to start it.</p>
        <div class="btn-stack">
          <a class="btn btn-primary" href="#/program?id=${encodeURIComponent(programId)}">View Program</a>
          <button type="button" class="btn btn-secondary" id="import-another-btn">Import Another</button>
        </div>
      </div>`;
    body.querySelector('#import-another-btn').addEventListener('click', () => renderChoose());
  }

  renderChoose();
}
